#! /bin/sh
FONT1="-*-profont-medium-*-*--12-*-*-*-*-*-*-1"
FONT2="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
PANEL_HEIGHT=15

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
while true ; do
echo "S$(date "+%b %d %Y %R")" > "$PANEL_FIFO" &
echo "B$(acpi -b| awk '{print $4}' | tr -d ',')" > "$PANEL_FIFO" &
echo "N$(iwconfig wlp5s0 | grep 'ESSID:' | awk '{gsub("ESSID:", " "); print $4}')" > "$PANEL_FIFO" &
echo "V$(amixer get Master | sed -nr '$ s:.*\[(.+%)].*:\1:p')" > "$PANEL_FIFO" &
echo "D$(df / | awk '/[0-9]%/{print $(NF-1)}')" > "$PANEL_FIFO" &
echo "C$(sensors | grep "Physical id 0" | cut -d+ -f2 | cut -d. -f1)" > "$PANEL_FIFO" &
sleep 1
done &


. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$FONT1","$FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -p &

wait
