#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{B$DARK}%{F$RED} %{B-}%{F-}%{F$PANNA} ${line#?} "
			;;
		T*)
			# xtitle output
			title="%{B$DARK}%{F$PANNA} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$DARK}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOCUSED_OCCUPIED_BG}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOCUSED_FREE_BG}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOCUSED_URGENT_BG}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$PANNA}%{B$COLOR_FREE_BG}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
						;;
					L*)
						# layout
						#wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						#;;
				esac
				shift
			done
			;;
		B*)
			#Battery
			battery="%{B$DARK}%{F$RED}  %{B-}%{F-}%{F$PANNA} ${line#?}%"
			;;
		N*)
			#SSID
			net="%{B$DARK}%{F$RED}  %{B-}%{F-}%{F$PANNA} ${line#?}"
			;;
		V*)
			#Sound
			volume="%{B$DARK}%{F$RED}  %{B-}%{F-}%{F$PANNA} ${line#?}%"
			;;		
		D*)
			#Disk Usage
			disk="%{B$DARK}%{F$RED}  %{B-}%{F-}%{F$PANNA} ${line#?}%"
			;;
		C*)
			#CPU Temp
			temp="%{B$DARK}%{F$RED}  %{B-}%{F-}%{F$PANNA} ${line#?}°C"
	esac

			system="%{B$RED}%{F$DARK} Arch-MSI  %{B-}%{F-}"
			

	printf "%s\n" "${system}${volume}${battery}%{c}${wm_infos}%{r}${net}${temp}${sys_infos}"
done
