#! /bin/sh

bspc config border_width        3
bspc config window_gap         50
bspc config split_ratio         0.52f
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 		30
#bspc config right_padding		15
#bspc config left_padding		15

bspc config focused_border_color	'#d64937'
bspc config urgent_border_color		'#dedede'

bspc config focus_follows_pointer true

bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf120') $(echo -e '\uf268') $(echo -e '\uf121') $(echo -e '\uf16a')
bspc rule -a Gimp desktop=^5 follow=on floating=on

bspc rule -a Chromium desktop=^3 follow=on
bspc rule -a mpv desktop=^5 floating=on follow=on
bspc rule -a subl3 desktop=^4 follow=on
bspc rule -a eclipse desktop=^4 follow=on
#bspc rule -a termite desktop=^2 follow=on
#bspc rule -a urxvt desktop=^5 follow=on
bspc rule -a nemo desktop=^1 follow=on